repos:
  - repo: https://github.com/psf/black
    rev: '20.8b1'
    hooks:
      - id: black
        exclude: |
          (?x)(
              ^pste/storage/|
              ^pste/migrations/
          )
        args:
          - '--check'
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
      - id: flake8
        exclude: |
          (?x)(
              ^pste/storage/|
              ^pste/migrations/
          )
