[tool.poetry]
name = "pste"
version = "0.3.0"
description = "Just a simple file hosting application inspired by the likes of pomf.se and teknik.io."
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1"
flask-login = "^0.4"
flask-sqlalchemy = "^2.4"
flask-migrate = "^2.5"
flask-wtf = "^0.14"
flask-assets = "^0.12"
libsass = "^0.19"
cssmin = "^0.2"
dynaconf = "^2.0"
passlib = { extras = ["argon2", "bcrypt"], version = "^1.7" }
python-magic = "^0.4"
humanize = "^0.5"
pygments = "^2.4"
pyyaml = "^5.1"
sentry-sdk = { extras = ["flask"], version = "^0.11", optional = true }
psycopg2 = { version = "^2.8", optional = true }
mysqlclient = { version = "^1.4", optional = true }
gunicorn = { version = "^19.9", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["mysqlclient"]
postgresql = ["psycopg2"]
sentry = ["sentry-sdk"]
gunicorn = ["gunicorn"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
