[tool.poetry]
name = "pste"
version = "0.3.0"
description = "Just a simple file hosting application inspired by the likes of pomf.se and teknik.io."
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "^3.6"
flask = "*"
flask-login = "*"
flask-sqlalchemy = "*"
flask-migrate = "*"
flask-wtf = "*"
environs = "*"
passlib = { extras = ["argon2", "bcrypt"], version = "*" }
python-magic = "*"
humanize = "*"
pygments = "*"
psycopg2 = { version = "*", optional = true }
mysqlclient = { version = "*", optional = true }
sentry-sdk = { version = "*", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["mysqlclient"]
postgres = ["psycopg2"]
sentry = ["sentry-sdk"]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
