# If you want to edit this file, copy it to a different location
# and set the FLASK_LOG_CONFIG environment variable to point to it.
version: 1
root:
    level: INFO
    handlers: [console]
formatters:
    console:
        format: '[%(asctime)s] [%(levelname)-5s] %(message)s'
        datefmt: '%H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        formatter: console
        stream: ext://sys.stdout
